name: invitation_party
description: "Elaria & Anton - Wedding Invitation"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.12.0

dependencies:
  flutter:
    sdk: flutter

  # State Management
  flutter_bloc: ^9.1.1
  equatable: ^2.0.7

  # DI
  get_it: ^8.0.3

  # Functional Programming
  dartz: ^0.10.1

  # Animations
  animated_text_kit: ^4.2.3
  flutter_animate: ^4.5.2

  # URL Launcher (for Maps link)
  url_launcher: ^6.3.1

  # Audio
  audioplayers: ^6.4.0

  # Fonts (Google Fonts)
  google_fonts: ^6.2.1

  # Utils
  intl: ^0.20.2
  visibility_detector: ^0.4.0+2
  confetti: ^0.8.0

  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/wedding_logo.png
    - assets/images/dark_floral_bg.png
    - assets/images/gallery_1.jpg
    - assets/images/gallery_2.jpg
    - assets/images/gallery_3.jpg
    - assets/images/gallery_4.jpg
    - assets/audio/wedding_music.mp3
